server:
  port: 8082

spring:
  application:
    name: task-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://mongoadmin:mongopassword@localhost:27017/task_db?authSource=admin}
      auto-index-creation: true

# JWT Configuration (Shares secret with Identity Service for stateless signature verification)
app:
  jwt:
    secret: ${JWT_SECRET:EzTaskEnterpriseJwtSecretKeyForSpringCloudGatewayVerification2026!}

# Swagger OpenAPI Documentation
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

# Observability & Metrics
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  endpoint:
    health:
      show-details: always
